name: 'merge-request-linter'

description: 'Lint your merge/pull requests'

branding:
  icon: 'check'
  color: 'black'

author: 'artarts36'

inputs:

  config:
    description: "Path to configuration file"
    required: false

  debug:
    description: "Run MR-Linter with debug mode"
    required: false
    default: false

  metrics:
    description: "Print full metrics"
    required: false
    default: false

runs:
  using: docker
  image: docker://artarts36/merge-request-linter
  args:
    - lint
  entrypoint: '$PWD/entrypoint.sh'
